# Function 1

In [3]:
import numpy as np

In [6]:
np.linspace(0,100,6)         #Array of 6 evenly divided values from 0 t 100

array([  0.,  20.,  40.,  60.,  80., 100.])

In [9]:
np.linspace(10,100,10)

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

# Function 2

In [10]:
np.arange(0,10,3)           #Array of values from 0 to less than 10 with step 3

array([0, 3, 6, 9])

In [11]:
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

# Function 3

In [13]:
np.identity(5)            # 5*5 array of 0 with 1 on diagonal (identity matrix)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [17]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

# Function 4

In [20]:
np.full((2*3),8)            # 2*3 array with all the values 4

array([[8, 8, 8],
       [8, 8, 8]])

In [21]:
np.full((2,5),5) 

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

# Function 5

In [23]:
np.random.randn(2,3)*100      # 6*7 array of random floats between 0-100

array([[-130.17549911,  -14.96547615, -116.54369748],
       [-147.05638754, -109.21974138, -240.85093191]])

# Function 6

In [26]:
a = np.array([3,5,7,9,18,24])
a.shape

(6,)

# Function 7

In [27]:
len(a)

6

# Function 8

In [29]:
a.ndim

1

# Function 9

In [33]:
a.size

6

# Function 10

In [31]:
a.dtype

dtype('int32')

In [34]:
a.dtype.name

'int32'

In [35]:
a.astype(int)

array([ 3,  5,  7,  9, 18, 24])

# Function 11

In [37]:
np.info(a)

class:  ndarray
shape:  (6,)
strides:  (4,)
itemsize:  4
aligned:  True
contiguous:  True
fortran:  True
data pointer: 0x5e5c28aa80
byteorder:  little
byteswap:  False
type: int32


# Function 12

In [45]:
np.copy(a) # copy a to a new memory

array([ 3,  5,  7,  9, 18, 24])

# Function 13

In [51]:
b = np.array([(1,2,3),(4,5,6)])       # Convert 2d array to 1d array
b.flatten()

array([1, 2, 3, 4, 5, 6])

# Function 14

In [52]:
b.T                 # Transposes (rows become column)

array([[1, 4],
       [2, 5],
       [3, 6]])

# Function 15

In [56]:
np.append(b,4)

array([1, 2, 3, 4, 5, 6, 4])

# Function 16

In [60]:
np.insert(b,5,7)

array([1, 2, 3, 4, 5, 7, 6])

# Function 17

In [63]:
x = ([1,3,5],[4,8,9])
arr1 = np.array(x)
arr1

array([[1, 3, 5],
       [4, 8, 9]])

In [64]:
arr2 = ([5,6,7],[8,9,0])
arr2

([5, 6, 7], [8, 9, 0])

In [65]:
np.concatenate((arr1,arr2),axis=0) # row wise

array([[1, 3, 5],
       [4, 8, 9],
       [5, 6, 7],
       [8, 9, 0]])

In [66]:
np.concatenate((arr1,arr2),axis=1) # column wise

array([[1, 3, 5, 5, 6, 7],
       [4, 8, 9, 8, 9, 0]])

In [67]:
np.vstack((arr1,arr2)) # row vise

array([[1, 3, 5],
       [4, 8, 9],
       [5, 6, 7],
       [8, 9, 0]])

In [68]:
np.hstack((arr1,arr2)) # column vise

array([[1, 3, 5, 5, 6, 7],
       [4, 8, 9, 8, 9, 0]])

# Function 18

In [74]:
arr2 = ([5,6,7],[8,9,0])
d = np.array(arr2)
np.split(d,[1],axis=0) # row vise

[array([[5, 6, 7]]), array([[8, 9, 0]])]

In [75]:
arr2 = ([5,6,7],[8,9,0])
d = np.array(arr2)
np.split(d,[1],axis=1) # column vise

[array([[5],
        [8]]),
 array([[6, 7],
        [9, 0]])]

In [76]:
arr2 = ([5,6,7],[8,9,0])
d = np.array(arr2)
np.hsplit(d,[1]) # column vise

[array([[5],
        [8]]),
 array([[6, 7],
        [9, 0]])]

 # Function 19

In [77]:
b.sum() # array wise sum

21

# Function 20

In [79]:
b.min() # array wise minimum value

1

# Function 21

In [80]:
b.max() # array wise maximum value

6

# Function 22

In [81]:
b.cumsum() # comulative value of all values

array([ 1,  3,  6, 10, 15, 21], dtype=int32)

# Function 23

In [82]:
b.mean()

3.5

# Function 24

In [86]:
np.median(b)

3.5

# Function 25

In [87]:
np.std(b)        # Standard deviation

1.707825127659933

# Function 26

In [88]:
np.argmax(b) # returns indices of the maximum elemrnt of the array in particular axis.

5

# Function 27

In [91]:
np.argmin(b) # return indeces of the min element of the array in a particular axis

0

# Function 28

In [92]:
np.var(b) # variance

2.9166666666666665

# Function 29

In [93]:
np.cumprod(b) # compute the comulative product of array elements over a great axis

array([  1,   2,   6,  24, 120, 720], dtype=int32)

# Function 30

In [94]:
a = np.array([1,2,3,4,5,6])

In [95]:
b = np.array([7,8,9,1,2,3])

In [96]:
a+b # Arithematic operations

array([ 8, 10, 12,  5,  7,  9])

# Function 31 

In [97]:
a-b

array([-6, -6, -6,  3,  3,  3])

# Function 32

In [98]:
np.divide(a,b)

array([0.14285714, 0.25      , 0.33333333, 4.        , 2.5       ,
       2.        ])

# Function 33

In [99]:
np.multiply(a,b)

array([ 7, 16, 27,  4, 10, 18])

# Function 34

In [100]:
np.exp(a)  # exponentiation

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 , 403.42879349])

# Function 35

In [101]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974])

# Function 36

In [102]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947])

# Function 37

In [105]:
np.floor(a) # compute the floor of each element

array([1., 2., 3., 4., 5., 6.])

# Function 38

In [107]:
a = np.array([1,2.4,5.6,2.4,7,1.9])

In [109]:
np.rint(a)     # round elements to nearest integer

array([1., 2., 6., 2., 7., 2.])

# Function 39

In [110]:
a

array([1. , 2.4, 5.6, 2.4, 7. , 1.9])

In [112]:
np.ceil(a) # smallest number greater than or equal to that number

array([1., 3., 6., 3., 7., 2.])

# Function 40 

In [114]:
a = [0,1,2,3,2.4,-1] # Compute the sign of each element:1(positive),0(zero),or-1(negative))
np.sign(a)

array([ 0.,  1.,  1.,  1.,  1., -1.])

# Function 41

In [115]:
np.abs(a)   # element wise for integer ,floating point ,or complex values

array([0. , 1. , 2. , 3. , 2.4, 1. ])

# Function 42

In [119]:
np.unique(a)  # compute the sorted and unique elements in a

array([-1. ,  0. ,  1. ,  2. ,  2.4,  3. ])

# Function 43

In [121]:
np.intersect1d(a,b) # elements common in a and b

array([1., 2., 3.])

# Function 44

In [123]:
np.setdiff1d(a,b) # elements in a that are not in b

array([-1. ,  0. ,  2.4])

# Function 45

In [124]:
np.power(a,4)

array([ 0.    ,  1.    , 16.    , 81.    , 33.1776,  1.    ])

# Function 46

In [143]:
a = np.array([3,4,5,6,7,8])
b = np.array([2,9,5,6,0,8])
np.in1d(a,b) # create a boolean array whether each element of x is contained in y

array([False, False,  True,  True, False,  True])

# Function 47

In [145]:
np.setxor1d(x,y) # set symmetrical differences;elements that are in either of the arrays,but not both

array([1, 2, 6, 7, 8, 9])

# Function 48

In [146]:
np.union1d(x,y) # compute the sorted union of elements

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Function 49

In [149]:
np.empty((7,7))

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

# Function 50

In [157]:
np.array([1,5,7,8])
np.repeat(d,3)
np.tile(d,2)

array([[5, 6, 7, 5, 6, 7],
       [8, 9, 0, 8, 9, 0]])